server.error.include-message: always
spring:
  config:
    activate:
      on-profile:
      - docker
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG

server.port: 8080
