server.port: 7020
server.error.include-message: always
app:
    product:
        host:localhost
        port:7021
    review:
        host:localhost
        port:7022
    
    recommendation:
        host:localhost
        port:7023


logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG