server.port: 8080
server.error.include-message: always
spring:
  config:
    activate:
      on-profile:
      - docker
app:
  product:
    host: product
    port: 8080
  review:
    host: review
    port: 8080
  recommendation:
    host: recommendation
    port: 8080

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG